version: '3.7'

services:

  siii_mongo:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: siii-chest
    ports:
      - '27017:27017'
    volumes:
      - './.data/db:/data/db'
